global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pandoc-service'
    static_configs:
      - targets: ['pandoc-service:9182']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
